# Generated by Django 4.1 on 2023-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("employee_title", models.CharField(max_length=50)),
                ("employee_name", models.CharField(max_length=50)),
                ("contact_info", models.CharField(max_length=50)),
            ],
            options={"db_table": "t_employee", "managed": True,},
        ),
        migrations.CreateModel(
            name="FixedEquipmentBase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mac", models.CharField(max_length=50)),
                ("site", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("lon", models.CharField(max_length=50)),
                ("lat", models.CharField(max_length=50)),
            ],
            options={"db_table": "t_fixed_equipment_base", "managed": True,},
        ),
        migrations.CreateModel(
            name="FixedEquipmentPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mac", models.CharField(max_length=50)),
                ("user_title", models.CharField(max_length=50)),
            ],
            options={"db_table": "t_fixed_equipment_permission", "managed": True,},
        ),
        migrations.CreateModel(
            name="FixedEquipmentStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mac", models.CharField(max_length=50)),
                ("rec_time", models.DateTimeField()),
                ("status", models.IntegerField()),
            ],
            options={"db_table": "t_fixed_equipment_status", "managed": True,},
        ),
        migrations.CreateModel(
            name="MobileDeviceBase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mac", models.CharField(max_length=50)),
                ("user_title", models.CharField(max_length=50)),
                ("employee_id", models.BigIntegerField()),
            ],
            options={"db_table": "t_mobile_device_base", "managed": True,},
        ),
        migrations.CreateModel(
            name="MobileDeviceStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mac", models.CharField(max_length=50)),
                ("rec_time", models.DateTimeField()),
                ("site", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("lon", models.CharField(max_length=50)),
                ("lat", models.CharField(max_length=50)),
            ],
            options={"db_table": "t_mobile_device_status", "managed": True,},
        ),
    ]
