# Generated by Django 4.2 on 2023-04-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedequipmentstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
